# Default values for OpenELB.
# This is a YAML-formatted file.
global:
  imageRegistry: docker.io # registry.cn-beijing.aliyuncs.com   docker.io
  tag: # "v1.0.0"
  imagePullSecrets: []

admission:
  image:
    # registry: docker.io
    repository: kubesphere/kube-webhook-certgen
    tag: v1.1.1
    pullPolicy: IfNotPresent

controller:
  monitorEnable: false
  monitorPort: 50052
  webhookPort: 443
  image:
    # registry: docker.io
    repository: kubesphere/openelb-controller
    tag: master
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  # nodeSelector:
  #   node-role.kubernetes.io/control-plane: ""
  # affinity:
  #   podAntiAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #       - weight: 100
  #         podAffinityTerm:
  #           labelSelector:
  #             matchLabels:
  #               app: openelb
  #               component: controller
  #           topologyKey: kubernetes.io/hostname
      
speaker:
  enable: true
  vip: false
  layer2: false
  # memberlistSecret: "" # default: openelb-speakers
  apiHosts: ":50051"
  monitorEnable: false
  monitorPort: 50052
  image:
    # registry: docker.io
    repository: kubesphere/openelb-speaker
    tag: master
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  # nodeSelector:
  #   kubernetes.io/os: linux
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: openelb.io/speaker-node
  #           operator: Exists
  # tolerations:
  #   - key: CriticalAddonsOnly
  #     operator: Exists
  #   - effect: NoSchedule
  #     key: node-role.kubernetes.io/master
  #   - effect: NoSchedule
  #     key: node-role.kubernetes.io/control-plane

customImage:
  enable: true
  forwardImage: ""  # kubesphere/openelb-forward:master
  proxyImage: ""    # kubesphere/openelb-proxy:master
