apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  coreTemplate:
    spec:
      replicas: {{ .Values.replicaCount.core }}
  replicantTemplate:
    spec:
        replicas: {{ .Values.replicaCount.replicant }}
  listenersServiceTemplate:
    spec:
      type: {{ .Values.service.type }}
  dashboardServiceTemplate:
    spec:
      type: {{ .Values.service.type }}