apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  listenersServiceTemplate:
    spec:
      type: {{ .Values.service.type }}
  dashboardServiceTemplate:
    spec:
      type: {{ .Values.service.type }}
  coreTemplate:
    metadata:
       labels:
         apps.kubernetes.io/managed-by: Helm
         apps.kubernetes.io/instance: emqx