apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  coreTemplate:
    spec:
      volumeClaimTemplates:
        resources:
          requests:
            storage: {{ .Values.volumeClaimTemplates.storage }}
        accessModes:
        - {{ .Values.volumeClaimTemplates.accessModes }}
      replicas: {{ .Values.replicaCount.core }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
  replicantTemplate:
    spec:
        replicas: {{ .Values.replicaCount.replicant }}
  listenersServiceTemplate:
    metadata:
      {{- if eq .Values.service.type "LoadBalancer" }}
      {{- with .Values.service.annotations }}
      annotations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- end }}
    spec:
      type: {{ .Values.service.type }}
  dashboardServiceTemplate:
    metadata:
      {{- if eq .Values.service.type "LoadBalancer" }}
      {{- with .Values.service.annotations }}
      annotations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- end }}
    spec:
      type: {{ .Values.service.type }}