{{- range $name, $_ := $.Values.persistentVolumeClaim }}
{{- if .enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{  .claimNam | default (printf "%s-%s" (include "fcu.fullname" $) $name) }}
  labels:
    {{- include "fcu.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
{{- end }}