apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-deamon-config
  namespace: dind-system
data:
  daemon.json: |
    {"insecure-registries": ["192.168.1.204:30002"]} 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-storage
  namespace: dind-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: docker-in-docker-svc
  namespace: dind-system
spec:
  type: NodePort
  selector:
    app: dind
  ports:
    - port: 2375
      protocol: TCP
      targetPort: 2375
      nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-in-docker-deploy
  namespace: dind-system
  labels:
    app: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: docker-dind-ct
        image: docker
        ports:
        - containerPort: 2375
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /etc/docker
      volumes:
      - name: config-volume
        configMap:
          name: docker-deamon-config
      - name: dind-storage
        persistentVolumeClaim:
          claimName: dind-storage        


