apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name:    {{ .Release.Name }} #clickhouse
  namespace:   {{ .Release.Namespace }} # alt-clickhouse  
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      serviceTemplate: service-template
      podTemplate: pod-template-resource-limit
  configuration:
    users:
      admin/password: {{ .Values.adminpassword }}
      admin/networks/ip: 
        - {{ .Values.allowedip }}
    clusters:
      - name: clickhouse
        layout:
          shardsCount: {{ .Values.clusters.shardsCount }}
          replicasCount: {{ .Values.clusters.replicasCount }}
  templates:
    podTemplate:
      - name: pod-template-resource-limit
        spec:
          containers:
            resources:
                requests:
                  memory: {{ .Values.podtemplate.requestsmem }}
                  cpu: {{ .Values.podtemplate.requestscpu }}
                limits:
                  memory: {{ .Values.podtemplate.limitsmem }}
                  cpu:  {{ .Values.podtemplate.limitscpu }}
    serviceTemplates:
    - name: service-template
      generateName: "service-{chi}"
      spec:
        ports:
        - name: http
          port: 8123
        - name: tcp
          port: 9000
        type: NodePort
    volumeClaimTemplates:
    - name: data-volume-template
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volumeClaimTemplates.storage }}
