apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql-backup.fullname" . }}
  labels:
    {{- include "mysql-backup.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  {{- if .Values.storageClassName }}
  storageClassName: "{{ .Values.storageClassName }}"
  {{- end }}