{{- with $.Values }}
{{- with .clientInfoSecret }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ .name | default (include "synology-csi.fullname" $ | printf "%s-client-info") }}
stringData:
  client-info.yaml: |
    ---
    {{- pick . "clients" | toYaml | nindent 4 }}
{{- end }}
{{- end }}

{{- with .smbUserSecret}}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ .name | default (include "synology-csi.fullname" $ | printf "%s-smb-user") }}
stringData: {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
