{{- if and .Values.speaker.enable .Values.speaker.layer2 (and (default "" .Values.speaker.memberlistSecret | trim | ne "")) }}
apiVersion: v1
data:
  key: {{ .Values.speaker.memberlistSecret | b64enc }}
kind: Secret
metadata:
  name: memberlist
{{- end }}
