apiVersion: v2
appVersion: 0.18.0
dependencies:
- alias: certmanager
  condition: certmanager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.12.4
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
home: https://github.com/OT-CONTAINER-KIT/redis-operator
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
maintainers:
- name: iamabhishek-dubey
- name: sandy724
- name: shubham-cmyk
name: redis-operator
sources:
- https://github.com/OT-CONTAINER-KIT/redis-operator
version: 0.18.3
