# Default values for clickhouse-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

spec:
  configuration:
    zookeeper:
      nodes:
        host: zk-cs-zookeep-cluster.alt-clickhouse
    users:
      adminpassword: clickhouse
      ip: 
        0.0.0.0/0
    clusters:
      layout:
        shardsCount: 2
        replicasCount: 2
  templates:
    volumeClaimTemplates:
      spec:
        resources:
          requests:
            storage: 5Gi