# Default values for clickhouse-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

zkhost: zk-cs-zookeep-cluster.clickhouse-system
adminpassword: clickhouse
allowedip: 0.0.0.0/0
clusters:
    shardsCount: 2
    replicasCount: 2
volumeClaimTemplates:
  storage: 8Gi
podtemplate:
  requestsmem: 4Gi
  requestscpu: 1
  limitsmem: 16Gi
  limitscpu: 6
configpro:
  readonly: "1"
  maxmemory: "22032385536"
podDistribution:
  number: 2
service:
  annotations: 
    lb.kubesphere.io/v1alpha1: openelb
  type: LoadBalancer