# Default values for clickhouse-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

zkhost: zk-cs-zookeep-cluster.alt-clickhouse
adminpassword: clickhouse
allowedip: 0.0.0.0/0
clusters:
    shardsCount: 2
    replicasCount: 2
volumeClaimTemplates:
  storage: 8Gi