{{- if .Values.persistentVolumeClaim.enabled  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.claimName| default (include "bcsu.fullname" .) }}
  labels:
    {{- include "bcsu.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
{{ end }}