apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dind.fullname" . }}
  labels:
    {{- include "dind.labels" . | nindent 4 }}
data:  
  daemon.json: |-  
    {  
      "insecure-registries": [
        "{{ .Values.insecureRegistries }}"
      ]
    } 