apiVersion: v1
kind: Service
metadata:
  name: {{ include "dind.fullname" . }}
  labels:
    {{- include "dind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: docker
      protocol: TCP
      name: docker
      {{- if .Values.service.nodeport }}
      nodePort: {{ .Values.service.nodeport }}
      {{- end }}
  selector:
    {{- include "dind.selectorLabels" . | nindent 4 }}
