# Default values for emqx-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 
  core: 4
  replicant: 0

image:
  repository: emqx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5"

service:
  type: NodePort
  
volumeClaimTemplates:
  storage: 10Gi
  accessModes: ReadWriteOnce


affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            apps.emqx.io/db-role: core
            apps.emqx.io/instance: emqx-cluster
            apps.emqx.io/managed-by: emqx-operator
        topologyKey: tiexiang.io/host-name