# Default values for emqx-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 
  core: 2
  replicant: 3

image:
  repository: emqx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5"

service:
  type: NodePort
  
volumeClaimTemplates:
  storage: 1Gi
  accessModes: ReadWriteOnce