apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-09-18T13:57:44Z"
  generation: 8
  name: nnj-yonganzhen-yaz014-1836303989153767425
  namespace: fcu-system
  resourceVersion: "5333286"
  uid: 3227e54a-49ea-4a6e-8ba6-13eace3f23b3
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      fcu-system: nnj-yonganzhen-yaz014-1836303989153767425
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fcu-system: nnj-yonganzhen-yaz014-1836303989153767425
    spec:
      containers:
      - image: 192.168.1.204:30002/dapeng/fcu-image-1726212168104:v2.0
        imagePullPolicy: Always
        name: nnj-yonganzhen-yaz014-1836303989153767425
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - mountPath: /app/data
          name: data
      - image: 192.168.1.204:30002/tiexiang/publish-server:v1.0.2
        imagePullPolicy: Always
        name: publish-server
        resources: {}
        volumeMounts:
        - mountPath: /app/config
          name: config
        - mountPath: /app/data
          name: data
        - mountPath: /app/log
          name: log
      volumes:
      - configMap:
          defaultMode: 420
          name: nnj-yonganzhen-yaz014-1836303989153767425-configmap
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: nnj-yonganzhen-yaz014-1836303989153767425-data
      - name: log
        persistentVolumeClaim:
          claimName: nnj-yonganzhen-yaz014-1836303989153767425-log
---          
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-subdir-external-provisioner
    volume.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-subdir-external-provisioner
  creationTimestamp: "2024-09-18T13:57:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: nnj-yonganzhen-yaz014-1836303989153767425-data
  namespace: fcu-system
  resourceVersion: "3633235"
  uid: e228a194-ab5d-4963-a541-0d2e4f9a5475
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-e228a194-ab5d-4963-a541-0d2e4f9a5475

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-subdir-external-provisioner
    volume.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-subdir-external-provisioner
  creationTimestamp: "2024-09-18T13:57:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: nnj-yonganzhen-yaz014-1836303989153767425-log
  namespace: fcu-system
  resourceVersion: "3633268"
  uid: 1bc00268-67d5-4d01-97ed-e59c594b6f7d
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-1bc00268-67d5-4d01-97ed-e59c594b6f7d

---
apiVersion: v1
data:
  config.json: '{"Device":{"DeviceClass":"Radar_Videos","FCUNum":"1836303989153767425","LineCode":"xgx","Manufacturer":"dapeng","ScopeClass":"ZhaLanJie"},"Level2Seconds":{"0":12000,"1":600,"2":300,"3":180,"4":60,"5":30,"6":10},"Logger":{"Level":"INFO","LogDir":"log"},"MQTTClient":{"CertFile":"","Host":"emqx-cluster-listeners.emqx-system","Password":"tx1726667868610","Port":"1883","Username":"nnj-yonganzhen-yaz014-1836303989153767425"},"MinioClient":{"AccessKey":"minio","CertCheck":"False","Endpoint":"minio.minio-system:443","SecretKey":"minio123"},"RPCServer":{"IP":"127.0.0.1","Port":"9999"},"Scene":{"BCSUNum":"yaz014","CompanyCode":"nnj","SceneClass":"KaiKuoDi","StationCode":"yonganzhen"}}'
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-18T13:57:44Z"
  name: nnj-yonganzhen-yaz014-1836303989153767425-configmap
  namespace: fcu-system
  resourceVersion: "3633223"
  uid: e374abc3-41e7-4ead-9aa6-c2acddd81ecf