apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.image.livesms.name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "livegbs.labels" . | nindent 4 }}
data:  
  livesms.ini: |-
    license_version=5

    [http]
    port={{ .Values.livesms.configmap.http.port }}

    [https]

    ; 可选配置开启 HTTPS 服务
    ; port=10011
    ; ssl_domain=localhost
    ; ssl_cert_file=ssl/localhost_cert.pem
    ; ssl_key_file=ssl/localhost_key.pem
    ; ssl_min_version=1.2
    [redis]
    ; 指向 CMS Redis
    host= {{ .Values.image.livecms.name }}-service
    port={{ .Values.livecms.configmap.redis.port }}
    password=livegbs@2024

    [sip]
    ; SMS SIP 服务器 IP/域名(必填)
    host= {{ .Values.image.livesms.name }}-service
    ; 配置 SMS 公网 IP(可选)
    wan_ip=
    serial=34020000002020000001
    realm=3402000000
    port={{ .Values.livesms.configmap.sip.port }}
    ; 可选配置0/1, 指示流媒体服务器使用公网 IP 接收国标下级流数据(可选)
    use_wan_ip_recv_stream=0
    ; 可选配置0/1, 用于级联场景, 指示上级使用公网 IP 取流(可选)
    use_wan_ip_send_stream=0
    ; 可选配置0/1, 用于级联场景, 指示使用随机空闲端口向上级推流(可选)
    use_random_port_send_stream=1
    ; 日志开关
    log=1
    download_dir=downloads
    ; 下载文件保存时间(秒), 若小于0永久保存
    download_file_reserve_seconds=86400

    [rtp]
    ; 收流端口区间, 对国标平台/设备开放
    tcp_port_range={{ .Values.livesms.configmap.rtp.tcp_port_range }}
    udp_port_range={{ .Values.livesms.configmap.rtp.udp_port_range }}
    ; 码流空闲超时(秒)
    idle_timeout_seconds=10
    ; 排序缓存大小
    sort_window_size=100
    ; 校验 PayloadType 开关(0-关闭, 1-开启)
    strict_payload_type=0

    [webrtc]
    ; 分发端口区间, 对浏览器开放
    udp_port_range={{ .Values.livesms.configmap.webrtc.udp_port_range }}

    [rtsp]
    ; 配置开启 RTSP 服务(可选)
    port=

    [record]
    ; 云端录像路径
    dir={{ .Values.livesms.configmap.record.dir }}
    ; 云端录像清理,剩余磁盘空间百分比阀值(单位百分比)
    clean_freespace_percent_threshold=5
    ; 云端录像清理,剩余磁盘空间大小阀值(单位MB)
    clean_freespace_size_threshold=5120

    ; 云端录像清理,录像超过N天执行清理(单位天)
    ; clean_over_days=7
    [service]
    name=LiveSMS_Service
    display_name=LiveSMS_Service
    description=LiveSMS_Service