apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.livecms.name }}-service
  labels:
    {{- include "livegbs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.livecms.service.type }}
  ports:  
    {{- range .Values.livecms.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .port }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "livegbs.selectorLabels" . | nindent 4 }}
