apiVersion: v1
kind: Service
metadata:
  name: {{ include "livegbs.fullname" . }}
  labels:
    {{- include "livegbs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.names }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .nodeport }}
      protocol: {{ .protocol }}
    {{- end }}      
  selector:
    {{- include "livegbs.selectorLabels" . | nindent 4 }}
    
